# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layoutui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayoutWindow(object):
    def setupUi(self, LayoutWindow):
        LayoutWindow.setObjectName("LayoutWindow")
        LayoutWindow.setWindowModality(QtCore.Qt.WindowModal)
        LayoutWindow.resize(1279, 868)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        LayoutWindow.setFont(font)
        LayoutWindow.setStyleSheet("QWidget {\n"
"    font: 14pt \"Verdana\";\n"
"}\n"
"QMainWindow {\n"
"    background-color:#dcdbdb;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(252,252,252);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: #92c2c2;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: #5aaaa5;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QLineEdit {\n"
"    color: #2b2b2a;\n"
"    border-width: 1px; \n"
"    border-radius: 3px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"QLabel {\n"
"        color: #2b2b2a;\n"
"}\n"
"QLCDNumber {\n"
"    color: rgb(0, 113, 255, 255);\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 3px;\n"
"    border-color: rgb(230, 230, 230);\n"
"    border-style: solid;\n"
"    background-color:rgb(207,207,207);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"    border-radius: 3px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"QMenuBar::item {\n"
"    color: #000000;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #000000;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    color: #000000;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#dcdbdb;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(223,223,223);\n"
"        background-color: #dcdbdb;\n"
"        border-style: solid;\n"
"        border-width: 2px;\n"
"        border-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:1px;\n"
"    border-left-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #2b2b2a;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:first:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"      border-bottom-width:1px;\n"
"      border-top-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #92c2c2, stop:1 #5aaaa5);\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #000000;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"    color: #000000;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"    color: #000000;\n"
"}\n"
"QRadioButton {\n"
"    color: 000000;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"    color: #a9b7c6;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#2b2b2a;\n"
"}\n"
"QSpinBox {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"QDoubleSpinBox {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"QTimeEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"QDateTimeEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"QDateEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #5aaaa5, stop:1 #008888);\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: rgb(181,181,181);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: rgb(181,181,181);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, y1:0.5, x1:1, y2:0.5, x2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 3px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(147, 200, 200);\n"
"    border-radius: 3px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 3px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(147, 200, 200);\n"
"    border-radius: 3px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   background: #7ca6a3;\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   background: #7ca6a3;\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-bottom-left-radius: 3px;\n"
"   background: #7ca6a3;\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-bottom-left-radius: 3px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-top-right-radius: 3px;\n"
"   background: #7ca6a3;\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-top-right-radius: 3px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"   border: 1px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-bottom-left-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"   border: 1px transparent grey;\n"
"   border-top-right-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"   border: 1px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-top-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"   border: 1px transparent grey;\n"
"   border-bottom-left-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"   background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"   background: none;\n"
"}  ")
        self.centralwidget = QtWidgets.QWidget(LayoutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbImage = QtWidgets.QLabel(self.centralwidget)
        self.lbImage.setText("")
        self.lbImage.setObjectName("lbImage")
        self.horizontalLayout.addWidget(self.lbImage)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbBlank = QtWidgets.QGroupBox(self.centralwidget)
        self.gbBlank.setObjectName("gbBlank")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbBlank)
        self.verticalLayout_4.setContentsMargins(5, -1, 0, -1)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_22 = QtWidgets.QLabel(self.gbBlank)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_29.addWidget(self.label_22)
        self.cbCodeType = QtWidgets.QComboBox(self.gbBlank)
        self.cbCodeType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbCodeType.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.cbCodeType.setObjectName("cbCodeType")
        self.cbCodeType.addItem("")
        self.cbCodeType.addItem("")
        self.horizontalLayout_29.addWidget(self.cbCodeType)
        self.horizontalLayout_29.setStretch(0, 1)
        self.horizontalLayout_29.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_16.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.leBack = QtWidgets.QLineEdit(self.gbBlank)
        self.leBack.setMaxLength(255)
        self.leBack.setClearButtonEnabled(False)
        self.leBack.setObjectName("leBack")
        self.horizontalLayout_16.addWidget(self.leBack)
        self.btnOpenBack = QtWidgets.QToolButton(self.gbBlank)
        self.btnOpenBack.setMinimumSize(QtCore.QSize(30, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../DataMatrix/sources/img/add_box_3d.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenBack.setIcon(icon)
        self.btnOpenBack.setObjectName("btnOpenBack")
        self.horizontalLayout_16.addWidget(self.btnOpenBack)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_29 = QtWidgets.QLabel(self.gbBlank)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_32.addWidget(self.label_29)
        self.leLabelWidth = QtWidgets.QLineEdit(self.gbBlank)
        self.leLabelWidth.setEnabled(True)
        self.leLabelWidth.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leLabelWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leLabelWidth.setObjectName("leLabelWidth")
        self.horizontalLayout_32.addWidget(self.leLabelWidth)
        self.label_38 = QtWidgets.QLabel(self.gbBlank)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_32.addWidget(self.label_38)
        self.leLabelHeight = QtWidgets.QLineEdit(self.gbBlank)
        self.leLabelHeight.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leLabelHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leLabelHeight.setObjectName("leLabelHeight")
        self.horizontalLayout_32.addWidget(self.leLabelHeight)
        self.horizontalLayout_32.setStretch(0, 3)
        self.horizontalLayout_32.setStretch(1, 1)
        self.horizontalLayout_32.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_27 = QtWidgets.QLabel(self.gbBlank)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_28.addWidget(self.label_27)
        self.leLeft = QtWidgets.QLineEdit(self.gbBlank)
        self.leLeft.setEnabled(True)
        self.leLeft.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leLeft.setMaxLength(4)
        self.leLeft.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leLeft.setObjectName("leLeft")
        self.horizontalLayout_28.addWidget(self.leLeft)
        self.label_32 = QtWidgets.QLabel(self.gbBlank)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_28.addWidget(self.label_32)
        self.leTop = QtWidgets.QLineEdit(self.gbBlank)
        self.leTop.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leTop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leTop.setObjectName("leTop")
        self.horizontalLayout_28.addWidget(self.leTop)
        self.horizontalLayout_28.setStretch(0, 3)
        self.horizontalLayout_28.setStretch(1, 1)
        self.horizontalLayout_28.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_28 = QtWidgets.QLabel(self.gbBlank)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_31.addWidget(self.label_28)
        self.leWidth = QtWidgets.QLineEdit(self.gbBlank)
        self.leWidth.setEnabled(True)
        self.leWidth.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leWidth.setObjectName("leWidth")
        self.horizontalLayout_31.addWidget(self.leWidth)
        self.label_36 = QtWidgets.QLabel(self.gbBlank)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_31.addWidget(self.label_36)
        self.leHeight = QtWidgets.QLineEdit(self.gbBlank)
        self.leHeight.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leHeight.setObjectName("leHeight")
        self.horizontalLayout_31.addWidget(self.leHeight)
        self.horizontalLayout_31.setStretch(0, 3)
        self.horizontalLayout_31.setStretch(1, 1)
        self.horizontalLayout_31.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_23 = QtWidgets.QLabel(self.gbBlank)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_34.addWidget(self.label_23)
        self.cbCodeRotate = QtWidgets.QComboBox(self.gbBlank)
        self.cbCodeRotate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbCodeRotate.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.cbCodeRotate.setObjectName("cbCodeRotate")
        self.cbCodeRotate.addItem("")
        self.cbCodeRotate.addItem("")
        self.cbCodeRotate.addItem("")
        self.cbCodeRotate.addItem("")
        self.horizontalLayout_34.addWidget(self.cbCodeRotate)
        self.label_24 = QtWidgets.QLabel(self.gbBlank)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_34.addWidget(self.label_24)
        self.cbCodeZoom = QtWidgets.QComboBox(self.gbBlank)
        self.cbCodeZoom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbCodeZoom.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.cbCodeZoom.setMaxCount(70)
        self.cbCodeZoom.setObjectName("cbCodeZoom")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.cbCodeZoom.addItem("")
        self.horizontalLayout_34.addWidget(self.cbCodeZoom)
        self.horizontalLayout_34.setStretch(0, 2)
        self.horizontalLayout_34.setStretch(1, 1)
        self.horizontalLayout_34.setStretch(2, 2)
        self.horizontalLayout_34.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtWidgets.QLabel(self.gbBlank)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        self.sbStartNum = QtWidgets.QSpinBox(self.gbBlank)
        self.sbStartNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbStartNum.setMinimum(1)
        self.sbStartNum.setMaximum(9999999)
        self.sbStartNum.setProperty("value", 1)
        self.sbStartNum.setObjectName("sbStartNum")
        self.horizontalLayout_20.addWidget(self.sbStartNum)
        self.horizontalLayout_20.setStretch(0, 3)
        self.horizontalLayout_20.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.cbText = QtWidgets.QGroupBox(self.gbBlank)
        self.cbText.setCheckable(True)
        self.cbText.setChecked(False)
        self.cbText.setObjectName("cbText")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.cbText)
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_20 = QtWidgets.QLabel(self.cbText)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_27.addWidget(self.label_20)
        self.cbNumeric = QtWidgets.QComboBox(self.cbText)
        self.cbNumeric.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbNumeric.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.cbNumeric.setObjectName("cbNumeric")
        self.cbNumeric.addItem("")
        self.cbNumeric.addItem("")
        self.cbNumeric.addItem("")
        self.cbNumeric.addItem("")
        self.cbNumeric.addItem("")
        self.horizontalLayout_27.addWidget(self.cbNumeric)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.cbText)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.leSampleText = QtWidgets.QLineEdit(self.cbText)
        self.leSampleText.setEnabled(False)
        self.leSampleText.setMaxLength(20)
        self.leSampleText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leSampleText.setClearButtonEnabled(True)
        self.leSampleText.setObjectName("leSampleText")
        self.horizontalLayout_19.addWidget(self.leSampleText)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_25 = QtWidgets.QLabel(self.cbText)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_30.addWidget(self.label_25)
        self.leTextLeft = QtWidgets.QLineEdit(self.cbText)
        self.leTextLeft.setEnabled(False)
        self.leTextLeft.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leTextLeft.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leTextLeft.setObjectName("leTextLeft")
        self.horizontalLayout_30.addWidget(self.leTextLeft)
        self.label_37 = QtWidgets.QLabel(self.cbText)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_30.addWidget(self.label_37)
        self.leTextTop = QtWidgets.QLineEdit(self.cbText)
        self.leTextTop.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leTextTop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leTextTop.setObjectName("leTextTop")
        self.horizontalLayout_30.addWidget(self.leTextTop)
        self.horizontalLayout_30.setStretch(0, 3)
        self.horizontalLayout_30.setStretch(1, 1)
        self.horizontalLayout_30.setStretch(3, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.cbText)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.sbFontSize = QtWidgets.QSpinBox(self.cbText)
        self.sbFontSize.setEnabled(False)
        self.sbFontSize.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.sbFontSize.setSuffix("")
        self.sbFontSize.setMinimum(1)
        self.sbFontSize.setMaximum(200)
        self.sbFontSize.setProperty("value", 18)
        self.sbFontSize.setObjectName("sbFontSize")
        self.horizontalLayout_15.addWidget(self.sbFontSize)
        self.horizontalLayout_15.setStretch(0, 3)
        self.horizontalLayout_15.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_19 = QtWidgets.QLabel(self.cbText)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_25.addWidget(self.label_19)
        self.cbTextRotate = QtWidgets.QComboBox(self.cbText)
        self.cbTextRotate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbTextRotate.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.cbTextRotate.setObjectName("cbTextRotate")
        self.cbTextRotate.addItem("")
        self.cbTextRotate.addItem("")
        self.cbTextRotate.addItem("")
        self.cbTextRotate.addItem("")
        self.horizontalLayout_25.addWidget(self.cbTextRotate)
        self.horizontalLayout_25.setStretch(0, 3)
        self.horizontalLayout_25.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.anchorText = QtWidgets.QGroupBox(self.cbText)
        self.anchorText.setCheckable(True)
        self.anchorText.setObjectName("anchorText")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.anchorText)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.anchorText)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.cbTextAllign = QtWidgets.QComboBox(self.anchorText)
        self.cbTextAllign.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbTextAllign.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.cbTextAllign.setObjectName("cbTextAllign")
        self.cbTextAllign.addItem("")
        self.cbTextAllign.addItem("")
        self.cbTextAllign.addItem("")
        self.cbTextAllign.addItem("")
        self.horizontalLayout_2.addWidget(self.cbTextAllign)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_10.addWidget(self.anchorText)
        self.verticalLayout_4.addWidget(self.cbText)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_4.setStretch(4, 1)
        self.verticalLayout_4.setStretch(5, 1)
        self.verticalLayout_4.setStretch(6, 1)
        self.verticalLayout_4.setStretch(7, 1)
        self.verticalLayout.addWidget(self.gbBlank)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnPreView = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPreView.sizePolicy().hasHeightForWidth())
        self.btnPreView.setSizePolicy(sizePolicy)
        self.btnPreView.setObjectName("btnPreView")
        self.verticalLayout.addWidget(self.btnPreView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnDefault = QtWidgets.QPushButton(self.centralwidget)
        self.btnDefault.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDefault.sizePolicy().hasHeightForWidth())
        self.btnDefault.setSizePolicy(sizePolicy)
        self.btnDefault.setObjectName("btnDefault")
        self.horizontalLayout_3.addWidget(self.btnDefault)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnOk = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOk.sizePolicy().hasHeightForWidth())
        self.btnOk.setSizePolicy(sizePolicy)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout_3.addWidget(self.btnOk)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        LayoutWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LayoutWindow)
        self.cbCodeZoom.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(LayoutWindow)

    def retranslateUi(self, LayoutWindow):
        _translate = QtCore.QCoreApplication.translate
        LayoutWindow.setWindowTitle(_translate("LayoutWindow", "Настройка параметров макета"))
        self.gbBlank.setTitle(_translate("LayoutWindow", "Настройка параметров макета этикетки:"))
        self.label_22.setText(_translate("LayoutWindow", "Тип кода:"))
        self.cbCodeType.setItemText(0, _translate("LayoutWindow", "GS1 Datamatrix"))
        self.cbCodeType.setItemText(1, _translate("LayoutWindow", "BarCode - BTS"))
        self.leBack.setPlaceholderText(_translate("LayoutWindow", "Файл шаблона этикетки"))
        self.btnOpenBack.setText(_translate("LayoutWindow", "..."))
        self.label_29.setText(_translate("LayoutWindow", "Размер этикетки:"))
        self.leLabelWidth.setText(_translate("LayoutWindow", "236"))
        self.label_38.setText(_translate("LayoutWindow", " : "))
        self.leLabelHeight.setText(_translate("LayoutWindow", "236"))
        self.label_27.setText(_translate("LayoutWindow", "Положение кода:"))
        self.leLeft.setText(_translate("LayoutWindow", "80"))
        self.label_32.setText(_translate("LayoutWindow", " : "))
        self.leTop.setText(_translate("LayoutWindow", "80"))
        self.label_28.setText(_translate("LayoutWindow", "Размер кода:"))
        self.leWidth.setText(_translate("LayoutWindow", "100"))
        self.label_36.setText(_translate("LayoutWindow", " : "))
        self.leHeight.setText(_translate("LayoutWindow", "100"))
        self.label_23.setText(_translate("LayoutWindow", "Вращение кода:"))
        self.cbCodeRotate.setItemText(0, _translate("LayoutWindow", "0"))
        self.cbCodeRotate.setItemText(1, _translate("LayoutWindow", "90"))
        self.cbCodeRotate.setItemText(2, _translate("LayoutWindow", "180"))
        self.cbCodeRotate.setItemText(3, _translate("LayoutWindow", "270"))
        self.label_24.setText(_translate("LayoutWindow", "  Масштаб:  "))
        self.cbCodeZoom.setCurrentText(_translate("LayoutWindow", "20"))
        self.cbCodeZoom.setItemText(0, _translate("LayoutWindow", "1"))
        self.cbCodeZoom.setItemText(1, _translate("LayoutWindow", "5"))
        self.cbCodeZoom.setItemText(2, _translate("LayoutWindow", "10"))
        self.cbCodeZoom.setItemText(3, _translate("LayoutWindow", "15"))
        self.cbCodeZoom.setItemText(4, _translate("LayoutWindow", "20"))
        self.cbCodeZoom.setItemText(5, _translate("LayoutWindow", "25"))
        self.cbCodeZoom.setItemText(6, _translate("LayoutWindow", "30"))
        self.cbCodeZoom.setItemText(7, _translate("LayoutWindow", "35"))
        self.cbCodeZoom.setItemText(8, _translate("LayoutWindow", "40"))
        self.cbCodeZoom.setItemText(9, _translate("LayoutWindow", "45"))
        self.cbCodeZoom.setItemText(10, _translate("LayoutWindow", "50"))
        self.cbCodeZoom.setItemText(11, _translate("LayoutWindow", "55"))
        self.cbCodeZoom.setItemText(12, _translate("LayoutWindow", "60"))
        self.cbCodeZoom.setItemText(13, _translate("LayoutWindow", "65"))
        self.cbCodeZoom.setItemText(14, _translate("LayoutWindow", "70"))
        self.label_15.setText(_translate("LayoutWindow", "Начать с номера:"))
        self.cbText.setTitle(_translate("LayoutWindow", "Добавить текстовую надпись"))
        self.label_20.setText(_translate("LayoutWindow", "Вид надписи:"))
        self.cbNumeric.setItemText(0, _translate("LayoutWindow", "Серийный номер"))
        self.cbNumeric.setItemText(1, _translate("LayoutWindow", "Порядковый номер"))
        self.cbNumeric.setItemText(2, _translate("LayoutWindow", "Форматированный код"))
        self.cbNumeric.setItemText(3, _translate("LayoutWindow", "Код Datamatrix"))
        self.cbNumeric.setItemText(4, _translate("LayoutWindow", "Номер короба"))
        self.label_14.setText(_translate("LayoutWindow", "Текст:"))
        self.leSampleText.setText(_translate("LayoutWindow", "21XXXXXXX"))
        self.label_25.setText(_translate("LayoutWindow", "Положение надписи:"))
        self.leTextLeft.setText(_translate("LayoutWindow", "80"))
        self.label_37.setText(_translate("LayoutWindow", " : "))
        self.leTextTop.setText(_translate("LayoutWindow", "80"))
        self.label_13.setText(_translate("LayoutWindow", "Размер шрифта:"))
        self.label_19.setText(_translate("LayoutWindow", "Вращение надписи:"))
        self.cbTextRotate.setItemText(0, _translate("LayoutWindow", "0"))
        self.cbTextRotate.setItemText(1, _translate("LayoutWindow", "90"))
        self.cbTextRotate.setItemText(2, _translate("LayoutWindow", "180"))
        self.cbTextRotate.setItemText(3, _translate("LayoutWindow", "270"))
        self.anchorText.setTitle(_translate("LayoutWindow", "Привязка надписи"))
        self.label_21.setText(_translate("LayoutWindow", "Положение относительно кода:"))
        self.cbTextAllign.setItemText(0, _translate("LayoutWindow", "Снизу"))
        self.cbTextAllign.setItemText(1, _translate("LayoutWindow", "Слева"))
        self.cbTextAllign.setItemText(2, _translate("LayoutWindow", "Сверху"))
        self.cbTextAllign.setItemText(3, _translate("LayoutWindow", "Справа"))
        self.btnPreView.setText(_translate("LayoutWindow", "Предварительный просмотр"))
        self.btnDefault.setText(_translate("LayoutWindow", "По умолчанию"))
        self.btnOk.setText(_translate("LayoutWindow", "Применить"))
        self.btnCancel.setText(_translate("LayoutWindow", "Отмена"))
