# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        LoginWindow.resize(390, 593)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono ExtraLight")
        font.setPointSize(16)
        LoginWindow.setFont(font)
        LoginWindow.setStyleSheet("QMainWindow {\n"
"  background-color : #e2e2e2;\n"
" border: 2px solid #4a8787;\n"
"}\n"
"\n"
"QLineEdit {\n"
"  background-color : #e2e2e2;\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #4a8787;\n"
"    border-width: 2px;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color : #e2e2e2;\n"
"    color: #474a4a;\n"
"    padding: 2px; \n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #474a4a;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #e2e2e2;\n"
"    color: #e2e2e2;\n"
"    border-color: #e2e2e2;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #7db5af;\n"
"    border: 1px solid #7db5af;\n"
"    color: #fff\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #4a8787;\n"
"    border: 1px solid #2f6363;\n"
"\n"
"}\n"
"QStatusBar {\n"
"    color:#4a8787;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbAuth = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setBold(False)
        font.setWeight(50)
        self.lbAuth.setFont(font)
        self.lbAuth.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbAuth.setLineWidth(1)
        self.lbAuth.setMidLineWidth(0)
        self.lbAuth.setText("")
        self.lbAuth.setPixmap(QtGui.QPixmap("sources/img/logo_truck.jpg"))
        self.lbAuth.setObjectName("lbAuth")
        self.verticalLayout.addWidget(self.lbAuth)
        self.leLogin = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.leLogin.setFont(font)
        self.leLogin.setAcceptDrops(False)
        self.leLogin.setAutoFillBackground(False)
        self.leLogin.setMaxLength(15)
        self.leLogin.setFrame(False)
        self.leLogin.setClearButtonEnabled(True)
        self.leLogin.setObjectName("leLogin")
        self.verticalLayout.addWidget(self.leLogin)
        self.lePassword = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lePassword.setFont(font)
        self.lePassword.setAcceptDrops(False)
        self.lePassword.setAutoFillBackground(False)
        self.lePassword.setMaxLength(15)
        self.lePassword.setFrame(False)
        self.lePassword.setObjectName("lePassword")
        self.verticalLayout.addWidget(self.lePassword)
        self.btnCreate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreate.sizePolicy().hasHeightForWidth())
        self.btnCreate.setSizePolicy(sizePolicy)
        self.btnCreate.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnCreate.setFont(font)
        self.btnCreate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCreate.setFlat(True)
        self.btnCreate.setObjectName("btnCreate")
        self.verticalLayout.addWidget(self.btnCreate)
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSign.sizePolicy().hasHeightForWidth())
        self.btnSign.setSizePolicy(sizePolicy)
        self.btnSign.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnSign.setFont(font)
        self.btnSign.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSign.setDefault(True)
        self.btnSign.setFlat(True)
        self.btnSign.setObjectName("btnSign")
        self.verticalLayout.addWidget(self.btnSign)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancel.setFont(font)
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel.setFlat(True)
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayout.addWidget(self.btnCancel)
        self.cbLocalConnection = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cbLocalConnection.setFont(font)
        self.cbLocalConnection.setObjectName("cbLocalConnection")
        self.verticalLayout.addWidget(self.cbLocalConnection)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Авторизация"))
        self.leLogin.setPlaceholderText(_translate("LoginWindow", "Логин"))
        self.lePassword.setPlaceholderText(_translate("LoginWindow", "Пароль"))
        self.btnCreate.setText(_translate("LoginWindow", "Регистрация"))
        self.btnSign.setText(_translate("LoginWindow", "Вход"))
        self.btnCancel.setText(_translate("LoginWindow", "Отмена"))
        self.cbLocalConnection.setText(_translate("LoginWindow", "Локальный компьютер"))
