# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SqlView(object):
    def setupUi(self, SqlView):
        SqlView.setObjectName("SqlView")
        SqlView.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(SqlView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tvSql = QtWidgets.QTableView(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tvSql.setFont(font)
        self.tvSql.setFrameShape(QtWidgets.QFrame.Box)
        self.tvSql.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tvSql.setMidLineWidth(1)
        self.tvSql.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tvSql.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvSql.setProperty("showDropIndicator", False)
        self.tvSql.setDragDropOverwriteMode(False)
        self.tvSql.setAlternatingRowColors(True)
        self.tvSql.setGridStyle(QtCore.Qt.DashLine)
        self.tvSql.setObjectName("tvSql")
        self.verticalLayout.addWidget(self.tvSql)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRun = QtWidgets.QPushButton(self.centralwidget)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout.addWidget(self.btnRun)
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        SqlView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SqlView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        SqlView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SqlView)
        self.statusbar.setObjectName("statusbar")
        SqlView.setStatusBar(self.statusbar)

        self.retranslateUi(SqlView)
        QtCore.QMetaObject.connectSlotsByName(SqlView)

    def retranslateUi(self, SqlView):
        _translate = QtCore.QCoreApplication.translate
        SqlView.setWindowTitle(_translate("SqlView", "MainWindow"))
        self.btnRun.setText(_translate("SqlView", "Запуск Sql скрипта"))
        self.btnClose.setText(_translate("SqlView", "Закрыть"))
